services:

  langfuse-web:
    environment:
      LANGFUSE_INIT_USER_EMAIL: admin@admin.com
      LANGFUSE_INIT_USER_PASSWORD: admin123
      LANGFUSE_INIT_ORG_ID: acme
      LANGFUSE_INIT_PROJECT_ID: test
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: pk-lf-123456
      LANGFUSE_INIT_PROJECT_SECRET_KEY: sk-lf-123456

  postgres:
    ports: !reset []

  langfuse-worker:
    ports: !reset []
  
  minio:
    ports: !reset []

  clickhouse:
    ports: !reset []

  redis:
    ports: !reset []
